### ISSUE TITLE
Example from Manual Fails

### ISSUE THREAD

**Issue by rlecover007** [automl/ParameterImportance#115]
Cloned the repository, navigated to examples/spear_qcp, ran 
``
pimp --scenario_file scenario.txt --history './*/runhistory.json' --modus forward-selection
``

which resulted in:
``
/home/rachel/.local/lib/python3.7/site-packages/pyparsing.py:2927: FutureWarning: Possible set intersection at position 3
  self.re = re.compile( self.reString )
Traceback (most recent call last):
  File "/home/rachel/.local/bin/pimp", line 5, in <module>
    from pimp.pimp import cmd_line_call
  File "/home/rachel/.local/lib/python3.7/site-packages/pimp/pimp.py", line 17, in <module>
    from smac.optimizer.objective import average_cost
ModuleNotFoundError: No module named 'smac.optimizer.objective'
``
```

**Comment by mlindauer** [comment]
Thanks for reporting that issue. I think that happens because of the recent SMAC release where we restructured the code quite a bit. Our main developer pf pimp (@AndreBiedenkapp) is on vacation this week. So, you have to wait a bit for a fix or you downgrade your SMAC version (e.g., by using a different conda env) for running pimp. 

Best,
Marius

PS: I would recommend to run CAVE (https://github.com/automl/CAVE) instead of pimp because it has the nicer interface. However, since CAVE imports pimp, it will have the same issue.

**Comment by rlecover007** [comment]
Thanks for pointing me towards CAVE. I'll give it a shot once I get a separate conda environment set up or whenever this issue gets fixed.

**Comment by rlecover007** [comment]
What's the latest version of SMAC that's known to work with CAVE/PyImp?

**Comment by mlindauer** [comment]
I haven't tried it, but I would expect that SMAC version 0.11. should work with Cave/pimp.

**Comment by rlecover007** [comment]
Thanks.

**Comment by shukon** [comment]
PyImp > 1.1.0 now supports SMAC 0.12.0. Since there are breaking changes introduced, please use PyImp 1.0.X for SMAC < 0.12.0.
