### ISSUE TITLE
ablation tuple-indices

### ISSUE THREAD

**Issue by shukon** [automl/ParameterImportance#38]
When performing ablation, I always get to this point. I'm not sure how it happens though, I thought the indexing is supposed to be on the configuration... I spent a couple hours fiddling with this, maybe you happen to have an idea?
```
ParameterImportance/scripts/evaluate.py -S scenario.txt -M ablation -H smac3-output_2017-08-22_14\:45\:45_\(772402\)_run1/runhistory.json -T smac3-output_2017-08-22_14\:45\:45_\(772402\)_run1/traj_aclib2.json
INFO:Importance:Reading Scenario file and files specified in the scenario
INFO:smac.scenario.scenario.Scenario:Reading scenario file: scenario.txt
INFO:smac.scenario.scenario.Scenario:Output to PIMP_ablation_2017_08_22_18:05:18
INFO:Importance:Reading Runhistory
INFO:Importance:#RunHistories found: 1
INFO:Importance:Combined number of Runhistory data points: 17
INFO:Importance:Number of Configurations: 7
INFO:Importance:Converting Data and constructing Model
INFO:Importance:Size of training X: (14, 80)
INFO:Importance:Size of training y: (14, 1)
INFO:Importance:Data was not imputed
INFO:Importance:Thus the size of X might be smaller than the datapoints in the RunHistory
INFO:Importance:Setting up Evaluation Method
Traceback (most recent call last):
  File "../../../ParameterImportance/scripts/evaluate.py", line 42, in <module>
    result = importance.evaluate_scenario(args.modus, sort_by=args.order)
  File "/home/shuki/ParameterImportance/pimp/importance/importance.py", line 383, in evaluate_scenario
    self.evaluator = evaluation_method
  File "/home/shuki/ParameterImportance/pimp/importance/importance.py", line 243, in evaluator
    logy=self.logged_y)
  File "/home/shuki/ParameterImportance/pimp/evaluator/ablation.py", line 30, in __init__
    self.delta = self._diff_in_source_and_target()
  File "/home/shuki/ParameterImportance/pimp/evaluator/ablation.py", line 324, in _diff_in_source_and_target
    if self.source[parameter] != self.target[parameter] and self.target[parameter] is not None:
TypeError: tuple indices must be integers or slices, not str
```

**Comment by AndreBiedenkapp** [comment]
Do you specify one trajectory fike to load or do you let pimp automatically load all trajectory files it can find in your directory?If you use the first option, my guess is that the bug is in the _load_incumbent method of the importance object. If i see that correctly, in line 94 the incumbent is a tupel. You'd have to access the first element of it to get the incumbent.As I am not near a computer right now I can't test it.If that doesn't work I'll have to take a closer look at it tomorrow.Best,AndréAm 22.08.2017 6:08 nachm. schrieb shukon <notifications@github.com>:When performing ablation, I always get to this point. I'm not sure how it happens though, I thought the indexing is supposed to be on the configuration... I spent a couple hours fiddling with this, maybe you happen to have an idea?
ParameterImportance/scripts/evaluate.py -S scenario.txt -M ablation -H smac3-output_2017-08-22_14\:45\:45_\(772402\)_run1/runhistory.json -T smac3-output_2017-08-22_14\:45\:45_\(772402\)_run1/traj_aclib2.json
INFO:Importance:Reading Scenario file and files specified in the scenario
INFO:smac.scenario.scenario.Scenario:Reading scenario file: scenario.txt
INFO:smac.scenario.scenario.Scenario:Output to PIMP_ablation_2017_08_22_18:05:18
INFO:Importance:Reading Runhistory
INFO:Importance:#RunHistories found: 1
INFO:Importance:Combined number of Runhistory data points: 17
INFO:Importance:Number of Configurations: 7
INFO:Importance:Converting Data and constructing Model
INFO:Importance:Size of training X: (14, 80)
INFO:Importance:Size of training y: (14, 1)
INFO:Importance:Data was not imputed
INFO:Importance:Thus the size of X might be smaller than the datapoints in the RunHistory
INFO:Importance:Setting up Evaluation Method
Traceback (most recent call last):
  File "../../../ParameterImportance/scripts/evaluate.py", line 42, in <module>
    result = importance.evaluate_scenario(args.modus, sort_by=args.order)
  File "/home/shuki/ParameterImportance/pimp/importance/importance.py", line 383, in evaluate_scenario
    self.evaluator = evaluation_method
  File "/home/shuki/ParameterImportance/pimp/importance/importance.py", line 243, in evaluator
    logy=self.logged_y)
  File "/home/shuki/ParameterImportance/pimp/evaluator/ablation.py", line 30, in __init__
    self.delta = self._diff_in_source_and_target()
  File "/home/shuki/ParameterImportance/pimp/evaluator/ablation.py", line 324, in _diff_in_source_and_target
    if self.source[parameter] != self.target[parameter] and self.target[parameter] is not None:
TypeError: tuple indices must be integers or slices, not str

**Comment by shukon** [comment]
Sounds reasonable. I will further investigate tomorrow and give you more information. Thanks!
Best,
Joshua
